{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.alertmanager.serviceAccountName" . }}
  labels: {{- include "prometheus-operator.alertmanager.labels" . | nindent 4 }}
{{- include "prometheus-operator.alertmanager.imagePullSecrets" . }}
{{- end }}
