apiVersion: v1
kind: Service
metadata:
  name: pi-endpoint
  namespace: monitoring
  labels:
    app: pi-endpoint
    release: prometheus-operator
spec:
  externalName: 192.168.1.132
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  type: ExternalName