{{- if and .Values.prometheus.enabled .Values.prometheus.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.prometheus.serviceAccountName" . }}
  labels: {{- include "prometheus-operator.prometheus.labels" . | nindent 4 }}
{{- include "prometheus-operator.prometheus.imagePullSecrets" . }}
{{- end }}
